// ============================================================
// STACKLY SALEM — Comprehensive Mock Data & Knowledge Base
// ============================================================

var _g = typeof window !== "undefined" ? window : (typeof globalThis !== "undefined" ? globalThis : this);
if (typeof window === "undefined") { var window = _g; }



var EXAM_CATEGORIES = window.EXAM_CATEGORIES = [
  {
    id: 'gre',
    name: 'GRE General Test',
    code: 'GRE',
    category: 'Graduate',
    description: 'Adaptive sectional scoring, advanced vocabulary flashcards, and quantitative geometry & algebra drills.',
    avgScoreJump: '+14 Pts',
    studentsCount: '128,000+',
    duration: '3h 45m',
    badgeColor: 'from-blue-500 to-indigo-600',
    iconName: 'GraduationCap',
    popularSubjects: ['Quantitative Reasoning', 'Verbal Reasoning', 'Analytical Writing'],
  },
  {
    id: 'gmat',
    name: 'GMAT Focus Edition',
    code: 'GMAT',
    category: 'Graduate',
    description: 'Master Data Insights, Quantitative Problem Solving, and Critical Reasoning with real-time percentile pacing.',
    avgScoreJump: '+90 Pts',
    studentsCount: '94,500+',
    duration: '2h 15m',
    badgeColor: 'from-amber-500 to-orange-600',
    iconName: 'Briefcase',
    popularSubjects: ['Data Insights', 'Quantitative', 'Verbal Reasoning'],
  },
  {
    id: 'mcat',
    name: 'MCAT Medical Prep',
    code: 'MCAT',
    category: 'Medical',
    description: 'Passage-based biological sciences, chemical foundations, CARS analysis, and psychological foundations.',
    avgScoreJump: '+11 Pts',
    studentsCount: '62,000+',
    duration: '7h 30m',
    badgeColor: 'from-emerald-500 to-teal-600',
    iconName: 'Stethoscope',
    popularSubjects: ['Bio/Biochem', 'Chem/Physics', 'CARS', 'Psych/Soc'],
  },
  {
    id: 'usmle',
    name: 'USMLE Step 1 & 2 CK',
    code: 'USMLE',
    category: 'Medical',
    description: 'High-yield clinical vignettes, organ system pathophysiology, pharmacology matrices, and mock exam simulations.',
    avgScoreJump: '99.2% Pass',
    studentsCount: '48,000+',
    duration: '8h 00m',
    badgeColor: 'from-cyan-500 to-blue-600',
    iconName: 'Activity',
    popularSubjects: ['Pathology', 'Pharmacology', 'Cardiovascular', 'Microbiology'],
  },
  {
    id: 'sat',
    name: 'Digital SAT Exam',
    code: 'SAT',
    category: 'Graduate',
    description: 'Multistage adaptive test engine, Desmos graphing calculator hacks, and high-frequency reading rhetoric.',
    avgScoreJump: '+210 Pts',
    studentsCount: '210,000+',
    duration: '2h 14m',
    badgeColor: 'from-purple-500 to-indigo-600',
    iconName: 'BookOpen',
    popularSubjects: ['Reading & Writing', 'Math Module 1', 'Math Module 2 Advanced'],
  },
  {
    id: 'gate',
    name: 'GATE & Tech Drills',
    code: 'GATE',
    category: 'Tech',
    description: 'Computer Science & Engineering core concepts: Algorithms, Operating Systems, Computer Networks, and Discrete Math.',
    avgScoreJump: 'Top 0.5% AIR',
    studentsCount: '85,000+',
    duration: '3h 00m',
    badgeColor: 'from-rose-500 to-pink-600',
    iconName: 'Cpu',
    popularSubjects: ['Data Structures & Algo', 'Computer Networks', 'Operating Systems', 'TOC & Compilers'],
  },
  {
    id: 'ielts',
    name: 'IELTS Academic & General',
    code: 'IELTS',
    category: 'Language',
    description: 'Live speaking room mock evaluations, writing task band 8+ structural templates, and audio listening drills.',
    avgScoreJump: '+1.5 Band',
    studentsCount: '160,000+',
    duration: '2h 45m',
    badgeColor: 'from-violet-500 to-fuchsia-600',
    iconName: 'Globe',
    popularSubjects: ['Academic Writing', 'Speaking Simulation', 'Listening Lab', 'Speed Reading'],
  },
  {
    id: 'lsat',
    name: 'LSAT Law School Exam',
    code: 'LSAT',
    category: 'Civil',
    description: 'Rigorous formal logic drills, reading comprehension for legal passages, and flaw-in-reasoning analysis.',
    avgScoreJump: '+12 Pts',
    studentsCount: '41,000+',
    duration: '3h 00m',
    badgeColor: 'from-sky-500 to-indigo-700',
    iconName: 'Scale',
    popularSubjects: ['Logical Reasoning', 'Reading Comprehension', 'Argument Evaluation'],
  },
  {
    id: 'tnpsc',
    name: 'TNPSC Group 1, 2 & 4',
    code: 'TNPSC',
    category: 'TNPSC',
    description: 'Comprehensive Tamil Nadu Civil Services: General Studies, Aptitude & Mental Ability, Tamil Language, Thirukkural & Salem Regional Administration.',
    avgScoreJump: '+28 Marks',
    studentsCount: '185,000+',
    duration: '3h 00m',
    badgeColor: 'from-amber-500 to-red-600',
    iconName: 'Building',
    popularSubjects: ['Tamil Society & Thirukkural', 'Indian Polity & Tamil Nadu Admin', 'Aptitude & Mental Ability', 'Current Affairs'],
  },
  {
    id: 'railways',
    name: 'Indian Railways RRB',
    code: 'RRB',
    category: 'Railways',
    description: 'RRB NTPC, ALP, Group D & Junior Engineer CBT simulations with speed arithmetic, general science, and technical aptitude.',
    avgScoreJump: '+22 Marks',
    studentsCount: '240,000+',
    duration: '1h 30m',
    badgeColor: 'from-emerald-600 to-teal-700',
    iconName: 'Train',
    popularSubjects: ['Speed Math & Train Problems', 'General Science & Physics', 'General Intelligence & Reasoning', 'Current Affairs'],
  },
  {
    id: 'banking',
    name: 'Banking & Financial (IBPS / SBI)',
    code: 'BANK',
    category: 'Banking',
    description: 'IBPS PO, SBI PO, RBI Grade B & Specialist Officer preparation with high-speed Data Interpretation, Syllogisms, and Banking Awareness.',
    avgScoreJump: '+19 Marks',
    studentsCount: '210,000+',
    duration: '2h 00m',
    badgeColor: 'from-blue-600 to-cyan-700',
    iconName: 'Landmark',
    popularSubjects: ['Data Interpretation (DI)', 'Puzzles & Seating Arrangement', 'Quantitative Aptitude', 'Banking & Monetary Policy'],
  },
  {
    id: 'aiml',
    name: 'AI & Machine Learning Certification',
    code: 'AI-ML',
    category: 'AI_ML',
    description: 'Master Deep Learning, Large Language Models (LLMs), PyTorch, Transformers, Computer Vision, and Applied MLOps Architecture.',
    avgScoreJump: '99.4% Pass',
    studentsCount: '92,000+',
    duration: '2h 30m',
    badgeColor: 'from-purple-600 to-indigo-800',
    iconName: 'Sparkles',
    popularSubjects: ['Transformer Architectures', 'Deep Neural Networks & Backprop', 'Loss Functions & Optimization', 'LLM Fine-tuning & Prompting'],
  },
  {
    id: 'programming',
    name: 'Full Stack & Software Engineering',
    code: 'TECH-CODE',
    category: 'Programming',
    description: 'Data Structures & Algorithms, Python, JavaScript/TypeScript, SQL Database Engineering, System Design, and Cloud DevOps.',
    avgScoreJump: 'Top 1% Tier',
    studentsCount: '135,000+',
    duration: '2h 00m',
    badgeColor: 'from-emerald-500 to-sky-600',
    iconName: 'Laptop',
    popularSubjects: ['Python & Algorithms (DSA)', 'JavaScript & Web Runtimes', 'SQL & Database Indexing', 'System Design & Distributed Systems'],
  },
  {
    id: 'history_gk',
    name: 'History & General Knowledge (GK)',
    code: 'HIST-GK',
    category: 'History_GK',
    description: 'Ancient, Medieval & Modern Indian History, World Geopolitics, Indian Constitution, General Science, and Static GK Drills.',
    avgScoreJump: '+32 Marks',
    studentsCount: '175,000+',
    duration: '2h 00m',
    badgeColor: 'from-orange-500 to-amber-700',
    iconName: 'BookOpen',
    popularSubjects: ['Indian Freedom Struggle', 'Indian Constitution & Polity', 'Ancient Civilizations & World History', 'General Science & Geography'],
  },
  {
    id: 'kids',
    name: 'Kids & Junior Olympiad (Grades 3-8)',
    code: 'KIDS-OLY',
    category: 'Kids',
    description: 'Fun, gamified STEM diagnostic tests, Math Olympiad puzzles, Science Bee questions, and cognitive logic drills for young learners.',
    avgScoreJump: 'Gold Medal Tier',
    studentsCount: '65,000+',
    duration: '45m',
    badgeColor: 'from-pink-500 to-rose-600',
    iconName: 'Award',
    popularSubjects: ['Mental Math & Patterns', 'Fun Science & Nature', 'Logical Thinking Puzzles', 'Language & Spelling Bee'],
  },
  {
    id: 'senior',
    name: 'Senior Citizens & Lifelong Learning',
    code: 'SENIOR-FIT',
    category: 'Senior',
    description: 'Brain & memory wellness assessments, digital banking & cybersecurity literacy, senior civil specialist exams, and heritage studies.',
    avgScoreJump: '+40% Sharpness',
    studentsCount: '38,000+',
    duration: '1h 00m',
    badgeColor: 'from-teal-500 to-emerald-700',
    iconName: 'Brain',
    popularSubjects: ['Safe Digital Banking & UPI', 'Cognitive Memory & Brain Fitness', 'Senior Specialist Services', 'Philosophy & Culture'],
  },
];

var COURSES = window.COURSES = [
  {
    id: 'course-gre-ultimate',
    title: 'GRE 330+ Comprehensive Masterclass',
    exam: 'GRE',
    category: 'Graduate',
    level: 'Mastery',
    instructor: {
      name: 'Dr. Julian Thorne',
      role: 'Head of Quantitative Reasoning (Harvard PhD, Perfect 170/170)',
      avatar: './assets/images/img-1534528741775-53.webp',
      rating: 4.96,
    },
    rating: 4.96,
    reviewsCount: 3842,
    enrolledStudents: 14200,
    durationWeeks: 12,
    videoHours: 85,
    practiceQuestions: 3600,
    fullMocksCount: 15,
    originalPrice: 399,
    salePrice: 249,
    badge: 'Bestseller',
    highlights: [
      '15 Section-adaptive full mock tests replicating ETS interface',
      'High-yield 1,200 vocabulary flashcard memory palace system',
      'Formula derivation shortcuts for speed quant under 75s/question',
      'Weekly live doubt resolution office hours with 99th percentile coaches',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Diagnostic Assessment & Baseline Mastery',
        lessons: ['Full Baseline Mock Test & IRT Calibration', 'Identifying Sectional Bottlenecks', 'Calculated Guessing & Pacing Rules'],
        quizzesCount: 4,
      },
      {
        moduleTitle: 'Module 2: Advanced Quantitative Reasoning & Shortcuts',
        lessons: ['Number Properties & Prime Factorization Speed Rules', 'Geometry & Coordinate Geometry Shortcuts', 'Data Interpretation & Probability Traps'],
        quizzesCount: 12,
      },
      {
        moduleTitle: 'Module 3: Verbal Reasoning & Text Completion Mastery',
        lessons: ['Sentence Equivalence Dual-Meaning Clues', 'Reading Comprehension Argument Mapping', 'Long Passage Speed Skimming'],
        quizzesCount: 10,
      },
      {
        moduleTitle: 'Module 4: Analytical Writing & Timed Simulators',
        lessons: ['Issue Essay 6.0 Scoring Templates', 'Constructing Cogent Logical Counterarguments', 'Simulated 3-Hour Exam Endurance Run'],
        quizzesCount: 6,
      },
    ],
  },
  {
    id: 'course-gmat-focus',
    title: 'GMAT Focus Edition 705+ Blueprint',
    exam: 'GMAT',
    category: 'Graduate',
    level: 'Comprehensive',
    instructor: {
      name: 'Elena Rostova, MBA',
      role: 'Former Wharton Admissions Evaluator & GMAT 770 Scorer',
      avatar: './assets/images/img-1573496359142-b8.webp',
      rating: 4.94,
    },
    rating: 4.94,
    reviewsCount: 2910,
    enrolledStudents: 9800,
    durationWeeks: 10,
    videoHours: 72,
    practiceQuestions: 2800,
    fullMocksCount: 12,
    originalPrice: 449,
    salePrice: 299,
    badge: 'Top Rated',
    highlights: [
      'Comprehensive Data Insights module with multi-source reasoning drills',
      'Question Edit feature strategies for the new GMAT Focus interface',
      'Critical Reasoning inference & assumption deconstruction trees',
      'Personalized review report with cognitive velocity breakdown',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: GMAT Focus Structural Dynamics',
        lessons: ['Understanding Section Selection Order Strategy', 'Scoring Algorithm: Penalty Curve Analysis', 'Benchmark Evaluation Test'],
        quizzesCount: 3,
      },
      {
        moduleTitle: 'Module 2: Data Insights & Graphic Interpretation',
        lessons: ['Multi-Source Reasoning Tabular Logic', 'Table Analysis & Two-Part Analysis Drills', 'Data Sufficiency Trap Recognition'],
        quizzesCount: 14,
      },
      {
        moduleTitle: 'Module 3: Quantitative Problem Solving',
        lessons: ['Algebraic Modeling & Word Problems', 'Rates, Work, and Overlapping Sets', 'Advanced Inequalities & Modulus Functions'],
        quizzesCount: 11,
      },
      {
        moduleTitle: 'Module 4: Critical Reasoning & Verbal Precision',
        lessons: ['Strengthen, Weaken & Boldface Propositions', 'Evaluating Flaws in Executive Arguments', 'Mock Exam Endurance Run 1-6'],
        quizzesCount: 8,
      },
    ],
  },
  {
    id: 'course-mcat-immersion',
    title: 'MCAT 520+ Clinical & Biological Immersion',
    exam: 'MCAT',
    category: 'Medical',
    level: 'Mastery',
    instructor: {
      name: 'Dr. Marcus Vance, MD',
      role: 'Johns Hopkins School of Medicine Alum & 100th Percentile MCAT Scorer',
      avatar: './assets/images/img-1537368910025-70.webp',
      rating: 4.98,
    },
    rating: 4.98,
    reviewsCount: 1840,
    enrolledStudents: 6400,
    durationWeeks: 16,
    videoHours: 120,
    practiceQuestions: 5200,
    fullMocksCount: 18,
    originalPrice: 599,
    salePrice: 389,
    badge: 'Premier',
    highlights: [
      'Over 5,000 passage-based questions cross-indexed by AAMC foundational concepts',
      'CARS strategy with rhetorical argument tracking and author perspective analysis',
      'High-yield biochemistry metabolic pathways mapped with 3D models',
      'Continuous 1-on-1 mentor guidance and score projection updates',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Chemical and Physical Foundations',
        lessons: ['Fluid Dynamics & Hemodynamics Analogs', 'Acid-Base Equilibria & Henderson-Hasselbalch', 'Spectroscopy & Molecular Separation'],
        quizzesCount: 15,
      },
      {
        moduleTitle: 'Module 2: Biological & Biochemical Foundations',
        lessons: ['Enzyme Kinetics, Michaelis-Menten, Lineweaver-Burk', 'Cellular Respiration & Glycolysis Regulation', 'Genetics, Epigenetics & Pedigree Analysis'],
        quizzesCount: 18,
      },
      {
        moduleTitle: 'Module 3: CARS Passage Deconstruction',
        lessons: ['Philosophy & Art Passage De-jargoning', 'Question Stems: Beyond the Text vs Within the Text', 'Eliminating 50/50 Traps in CARS'],
        quizzesCount: 12,
      },
      {
        moduleTitle: 'Module 4: Psychological, Social, and Biological Foundations',
        lessons: ['Cognitive Biases & Memory Schemas', 'Social Stratification & Sociological Theories', 'Full-Length Proctored Mocks 1-18'],
        quizzesCount: 14,
      },
    ],
  },
  {
    id: 'course-digital-sat',
    title: 'Digital SAT 1550+ Fast-Track Blueprint',
    exam: 'SAT',
    category: 'Graduate',
    level: 'Intermediate',
    instructor: {
      name: 'Claire Kensington',
      role: 'SAT Master Coach & Stanford Graduate (Trained 18,000+ Students)',
      avatar: './assets/images/img-1580489944761-15.webp',
      rating: 4.92,
    },
    rating: 4.92,
    reviewsCount: 4610,
    enrolledStudents: 22000,
    durationWeeks: 8,
    videoHours: 54,
    practiceQuestions: 2400,
    fullMocksCount: 14,
    originalPrice: 299,
    salePrice: 179,
    badge: 'Popular',
    highlights: [
      'Master the built-in Desmos graphing calculator to solve hard math in 20 seconds',
      'Adaptive Module 2 difficulty unlock system with rigorous 750+ question banks',
      'Vocabulary in context patterns and transitions question formulas',
      'Live score jump guarantee with refund protection',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Digital SAT Platform Secrets',
        lessons: ['How the Multistage Adaptive Engine Routes You', 'Desmos Built-In Calculator Speed Hacks', 'Time Allocation per Question Type'],
        quizzesCount: 4,
      },
      {
        moduleTitle: 'Module 2: Reading & Writing Mastery',
        lessons: ['Command of Evidence: Textual and Quantitative', 'Craft and Structure: Words in Context', 'Standard English Conventions: Punctuation Traps'],
        quizzesCount: 10,
      },
      {
        moduleTitle: 'Module 3: Advanced Math Module 2',
        lessons: ['Heart of Algebra & Systems of Equations', 'Passport to Advanced Math: Non-linear Equations', 'Problem Solving and Data Analysis with Graphs'],
        quizzesCount: 14,
      },
      {
        moduleTitle: 'Module 4: 10 Full Adaptive Mock Drills',
        lessons: ['Timed Adaptive Full Test 1-5', 'Deep Review & Error Log Analysis', 'Mock 6-10 with Target Score Validation'],
        quizzesCount: 10,
      },
    ],
  },
  {
    id: 'course-gate-cs',
    title: 'GATE CS & IT 2026 Complete Ranker Program',
    exam: 'GATE',
    category: 'Tech',
    level: 'Comprehensive',
    instructor: {
      name: 'Prof. Arvind Nambiar',
      role: 'Ex-IIT Faculty & Top 5 AIR GATE CS Ranker',
      avatar: './assets/images/img-1507003211169-0a.webp',
      rating: 4.95,
    },
    rating: 4.95,
    reviewsCount: 3120,
    enrolledStudents: 11400,
    durationWeeks: 20,
    videoHours: 140,
    practiceQuestions: 4500,
    fullMocksCount: 20,
    originalPrice: 429,
    salePrice: 279,
    badge: 'Specialized',
    highlights: [
      'Covers 100% of revised GATE CS syllabus including AI, ML and Discrete Math',
      'Virtual Scientific Calculator efficiency tricks and numerical answer type (NAT) tactics',
      'Previous 25 years question analysis with deep conceptual proofs',
      'Subject-wise tests, multi-subject tests and national mock series',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Data Structures, Algorithms & C Programming',
        lessons: ['Asymptotic Analysis & Recurrences', 'Dynamic Programming & Graph Algorithms', 'Hashing, Trees & Heaps Implementation'],
        quizzesCount: 16,
      },
      {
        moduleTitle: 'Module 2: Theory of Computation & Compiler Design',
        lessons: ['Regular Languages, DFA & NFA Minimization', 'Turing Machines & Decidability Limits', 'Parsing Techniques (LL, LR, LALR)'],
        quizzesCount: 14,
      },
      {
        moduleTitle: 'Module 3: Operating Systems & Computer Networks',
        lessons: ['CPU Scheduling, Deadlock & Memory Management', 'Paging, Virtual Memory & Thrashing', 'TCP/IP, Routing & Congestion Control'],
        quizzesCount: 15,
      },
      {
        moduleTitle: 'Module 4: Database Systems & Digital Logic',
        lessons: ['Relational Algebra, SQL & Normalization up to BCNF', 'Transaction Concurrency & ACID Enforcement', 'K-Maps, Combinational & Sequential Circuits'],
        quizzesCount: 12,
      },
    ],
  },
  {
    id: 'course-ielts-mastery',
    title: 'IELTS Academic Band 8.5 Masterclass',
    exam: 'IELTS',
    category: 'Language',
    level: 'Beginner',
    instructor: {
      name: 'Sarah Jenkins, MA TESOL',
      role: 'Cambridge Certified Senior Examiner with 15+ Yrs Experience',
      avatar: './assets/images/img-1544005313-94ddf.webp',
      rating: 4.93,
    },
    rating: 4.93,
    reviewsCount: 5120,
    enrolledStudents: 19500,
    durationWeeks: 6,
    videoHours: 48,
    practiceQuestions: 1800,
    fullMocksCount: 12,
    originalPrice: 249,
    salePrice: 149,
    badge: 'High Impact',
    highlights: [
      'Live AI speech evaluator for pronunciation and lexical diversity',
      'Band 9 Task 1 & Task 2 essay templates with grammatical range guidelines',
      'Real native speaker accent audio library (British, Australian, American, Canadian)',
      '12 Full-length computer-delivered mock tests with automatic grading',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Academic Writing Task 1 & Task 2',
        lessons: ['Describing Trends, Pie Charts & Complex Flowcharts', 'Opinion, Discussion & Problem-Solution Essay Structures', 'Grammatical Range: Inversion & Subjunctive Moods'],
        quizzesCount: 8,
      },
      {
        moduleTitle: 'Module 2: Speaking Fluency & Topic Cards',
        lessons: ['Part 1 Introduction & Natural Fillers', 'Part 2 Cue Card: 2-Minute Structured Monologue', 'Part 3 Abstract Discussion Strategies'],
        quizzesCount: 10,
      },
      {
        moduleTitle: 'Module 3: Listening Comprehension Lab',
        lessons: ['Section 4 Academic Lecture Note-taking', 'Distractor Identification & Spelling Conventions', 'Maps, Floorplans & Diagram Labeling'],
        quizzesCount: 10,
      },
      {
        moduleTitle: 'Module 4: Speed Reading & Skimming Drills',
        lessons: ['True/False/Not Given Trap Elimination', 'Matching Headings with Structural Signposts', '6 Timed Full Mocks with Examiner Feedback'],
        quizzesCount: 6,
      },
    ],
  },
  {
    id: 'course-tnpsc-mastery',
    title: 'TNPSC Group 1, 2 & 4 Combined Officer Accelerator',
    exam: 'TNPSC',
    category: 'TNPSC',
    level: 'Comprehensive',
    instructor: {
      name: 'Dr. K. Senthil Kumar, Ph.D.',
      role: 'Former TNPSC Board Resource Person & Tamil Nadu Administrative Scholar',
      avatar: './assets/images/img-1507003211169-0a.webp',
      rating: 4.97,
    },
    rating: 4.97,
    reviewsCount: 4210,
    enrolledStudents: 28400,
    durationWeeks: 16,
    videoHours: 110,
    practiceQuestions: 5200,
    fullMocksCount: 20,
    originalPrice: 199,
    salePrice: 119,
    badge: 'Salem Flagship',
    highlights: [
      'Bilingual coverage (Tamil & English) for General Studies & Aptitude',
      'Thirukkural 100-mark deep analytical essay & ethics framework',
      'Salem & Tamil Nadu District Administrative case studies & socio-economic history',
      '20 Full-length state-calibrated OMR & CBT simulation mock exams',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: General Studies & Indian Polity',
        lessons: ['Constitution of India & Amendments', 'Panchayati Raj & Tamil Nadu Local Governance', 'Economy of Tamil Nadu & Salem Industrial Growth'],
        quizzesCount: 12,
      },
      {
        moduleTitle: 'Module 2: Tamil Society, Culture & Thirukkural',
        lessons: ['Sangam Literature & Archeological Excavations', 'Thirukkural Administrative & Ethical Principles', 'Social Movements in Tamil Nadu & Justice Party'],
        quizzesCount: 15,
      },
      {
        moduleTitle: 'Module 3: Aptitude & Mental Ability Reasoning',
        lessons: ['Simplification, HCF/LCM & Percentage Tricks', 'Compound Interest & Time/Work Efficiency', 'Logical Reasoning & Visual Puzzles'],
        quizzesCount: 10,
      },
    ],
  },
  {
    id: 'course-rrb-ntpc',
    title: 'Indian Railways RRB NTPC & ALP Complete Mission',
    exam: 'RRB',
    category: 'Railways',
    level: 'Intermediate',
    instructor: {
      name: 'Er. Rajesh Narayanan',
      role: 'Former Senior Section Engineer (Southern Railways) & Aptitude Trainer',
      avatar: './assets/images/img-1500648767791-00.webp',
      rating: 4.94,
    },
    rating: 4.94,
    reviewsCount: 3890,
    enrolledStudents: 34100,
    durationWeeks: 10,
    videoHours: 72,
    practiceQuestions: 4500,
    fullMocksCount: 18,
    originalPrice: 179,
    salePrice: 99,
    badge: 'Bestseller',
    highlights: [
      'Rapid Train & Relative Speed shortcut formulas (solve under 45 seconds)',
      'NCERT Physics, Chemistry & Biology complete concept question bank',
      'CBT Stage 1 & Stage 2 exact computer test simulation interface',
      'Salem Division Railway apprentice & recruitment previous 10-year papers',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Speed Arithmetic & Railway Quant',
        lessons: ['Train Crossing & Relative Motion', 'Time, Speed, Distance & Boats', 'Profit, Loss & Ratio Proportions'],
        quizzesCount: 14,
      },
      {
        moduleTitle: 'Module 2: General Science for CBT 1 & 2',
        lessons: ['Newtonian Mechanics & Electricity (25kV Traction)', 'Periodic Table & Chemical Reactions', 'Human Physiology & Nutrition'],
        quizzesCount: 12,
      },
      {
        moduleTitle: 'Module 3: General Intelligence & Reasoning',
        lessons: ['Coding-Decoding & Direction Sense', 'Venn Diagrams & Syllogistic Deductions', 'Mathematical Operations & Blood Relations'],
        quizzesCount: 10,
      },
    ],
  },
  {
    id: 'course-banking-po',
    title: 'Ultimate Banking IBPS PO & SBI PO Prelims + Mains',
    exam: 'BANK',
    category: 'Banking',
    level: 'Mastery',
    instructor: {
      name: 'Vandana Ramesh, CAIIB',
      role: 'Ex-Chief Manager (State Bank of India) & Banking Faculty',
      avatar: './assets/images/img-1573497019940-1c.webp',
      rating: 4.96,
    },
    rating: 4.96,
    reviewsCount: 4610,
    enrolledStudents: 31200,
    durationWeeks: 12,
    videoHours: 90,
    practiceQuestions: 5000,
    fullMocksCount: 25,
    originalPrice: 229,
    salePrice: 129,
    badge: 'Popular',
    highlights: [
      'High-level 3-variable Seating Arrangement & Floor Puzzles',
      'Advanced Radar, Missing & Caselet Data Interpretation (DI)',
      'RBI Monetary Policy, Repo Rate & Banking Awareness 2026',
      'Daily 20-minute timed speed booster drills for quant & reasoning',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Quantitative Aptitude & High-Speed DI',
        lessons: ['Missing & Wrong Number Series under 30s', 'Quadratic Equations & Inequalities', 'Complex Caselet & Tabular Data Interpretation'],
        quizzesCount: 15,
      },
      {
        moduleTitle: 'Module 2: Reasoning & Seating Puzzles',
        lessons: ['Circular & Parallel Row Arrangement with Multiple Attributes', 'Syllogisms (Only a few / Possibility cases)', 'Input-Output Machine Reasoning for Mains'],
        quizzesCount: 14,
      },
      {
        moduleTitle: 'Module 3: Banking & Financial Awareness',
        lessons: ['RBI Functions, MPC & Inflation Targeting', 'Basel III Accords, NPAs & SARFAESI Act', 'Digital Banking, UPI & Cyber Security in Banking'],
        quizzesCount: 12,
      },
    ],
  },
  {
    id: 'course-aiml-eng',
    title: 'AI & Machine Learning Engineer Professional Certification',
    exam: 'AI-ML',
    category: 'AI_ML',
    level: 'Mastery',
    instructor: {
      name: 'Dr. Arunachalam S., Ph.D.',
      role: 'Principal AI Scientist & Ex-DeepMind Researcher',
      avatar: './assets/images/img-1534528741775-53.webp',
      rating: 4.98,
    },
    rating: 4.98,
    reviewsCount: 3190,
    enrolledStudents: 18900,
    durationWeeks: 14,
    videoHours: 95,
    practiceQuestions: 3200,
    fullMocksCount: 12,
    originalPrice: 299,
    salePrice: 189,
    badge: 'Trending Tech',
    highlights: [
      'Transformer Architecture, Multi-Head Attention & KV Cache optimization',
      'Gradient Descent, Backpropagation & Loss Function mathematical proofs',
      'Fine-tuning LLMs (LoRA, QLoRA, RLHF) & Vector Embeddings',
      '12 Industry-standard proctored coding and theoretical certification exams',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Foundations of Machine Learning',
        lessons: ['Linear & Logistic Regression with Regularization (L1/L2)', 'Decision Trees, Random Forests & XGBoost', 'Bias-Variance Tradeoff & Cross-Validation'],
        quizzesCount: 10,
      },
      {
        moduleTitle: 'Module 2: Deep Learning & Neural Architectures',
        lessons: ['Feedforward Networks, Activations & Vanishing Gradients', 'Convolutional Networks & Computer Vision', 'Recurrent Networks, LSTMs & Sequence Modeling'],
        quizzesCount: 12,
      },
      {
        moduleTitle: 'Module 3: Generative AI, Transformers & LLMs',
        lessons: ['Self-Attention Mechanism & Quadratic Complexity', 'Encoder-Decoder vs Decoder-Only Models', 'Quantization, Inference Optimization & MLOps Pipelines'],
        quizzesCount: 10,
      },
    ],
  },
  {
    id: 'course-programming-fullstack',
    title: 'Full-Stack Software Engineering & DSA Code Master',
    exam: 'TECH-CODE',
    category: 'Programming',
    level: 'Mastery',
    instructor: {
      name: 'Karthik Subramanian',
      role: 'Staff Software Architect & FAANG Tech Lead',
      avatar: './assets/images/img-1507003211169-0a.webp',
      rating: 4.95,
    },
    rating: 4.95,
    reviewsCount: 4120,
    enrolledStudents: 22400,
    durationWeeks: 12,
    videoHours: 88,
    practiceQuestions: 3800,
    fullMocksCount: 15,
    originalPrice: 249,
    salePrice: 149,
    badge: 'Top Pick',
    highlights: [
      'Data Structures & Algorithms: Graphs, Trees, Dynamic Programming',
      'JavaScript Engine: Event Loop, Microtasks, Memory Leaks & Closures',
      'Database Indexing: B-Trees, Query Execution Plans & ACID guarantees',
      'Live code assessment arena with automated test suite validation',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Core Data Structures & Algorithm Design',
        lessons: ['Arrays, Hash Maps & Two-Pointer Patterns', 'Binary Search, Trees & Graph Traversals (BFS/DFS)', 'Dynamic Programming: Memoization & Tabulation'],
        quizzesCount: 15,
      },
      {
        moduleTitle: 'Module 2: Advanced JavaScript, TypeScript & Full Stack',
        lessons: ['Asynchronous Runtimes, Promises & Event Loop', 'React Re-render Optimizations & State Architectures', 'RESTful & GraphQL API Design with Middleware'],
        quizzesCount: 12,
      },
      {
        moduleTitle: 'Module 3: Database Engineering & System Design',
        lessons: ['Relational vs NoSQL, Sharding & Replication', 'SQL Complex Joins, Window Functions & Index Optimization', 'Distributed Caching, Load Balancing & Rate Limiting'],
        quizzesCount: 12,
      },
    ],
  },
  {
    id: 'course-kids-olympiad',
    title: 'Junior Scholars STEM & Math Olympiad (Grades 3-8)',
    exam: 'KIDS-OLY',
    category: 'Kids',
    level: 'Beginner',
    instructor: {
      name: 'Pooja Narayanan, M.Ed.',
      role: 'National Olympiad Medalist Coach & STEM Educator',
      avatar: './assets/images/img-1494790108377-be.webp',
      rating: 4.98,
    },
    rating: 4.98,
    reviewsCount: 2840,
    enrolledStudents: 14500,
    durationWeeks: 8,
    videoHours: 40,
    practiceQuestions: 2200,
    fullMocksCount: 10,
    originalPrice: 149,
    salePrice: 89,
    badge: 'Kid Friendly',
    highlights: [
      'Visual mental math puzzles & gamified speed challenges',
      'Hands-on science experiments explained with vivid illustrations',
      'Spell Bee pronunciation audio & vocabulary flashcards',
      'Child-safe, distraction-free testing environment with celebratory badges',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Number Magic & Geometry Puzzles',
        lessons: ['Magic Number Squares & Pattern Sequences', 'Fun Fractions, Decimals & Clocks', 'Shapes, Symmetry & Spatial Origami'],
        quizzesCount: 10,
      },
      {
        moduleTitle: 'Module 2: Wonders of Science & Nature',
        lessons: ['Solar System & Space Explorations', 'Plants, Animals & Habitats', 'Forces, Magnets & Light Rays'],
        quizzesCount: 10,
      },
    ],
  },
  {
    id: 'course-senior-learning',
    title: 'Senior Citizens Digital Literacy & Cognitive Sharpness',
    exam: 'SENIOR-FIT',
    category: 'Senior',
    level: 'Beginner',
    instructor: {
      name: 'Prof. Ananya Sundaram, M.Sc.',
      role: 'Head of Cognitive Gerontology & Lifelong Learning at Salem HQ',
      avatar: './assets/images/img-1544005313-94ddf.webp',
      rating: 4.99,
    },
    rating: 4.99,
    reviewsCount: 1980,
    enrolledStudents: 9800,
    durationWeeks: 6,
    videoHours: 30,
    practiceQuestions: 1200,
    fullMocksCount: 8,
    originalPrice: 129,
    salePrice: 69,
    badge: 'Gentle Paced',
    highlights: [
      'Safe Digital Banking: UPI security, avoiding scam calls & OTP protection',
      'Daily Brain Agility: Crosswords, memory exercises & cognitive puzzles',
      'Smartphone navigation: Video calling, digital health records & government portals',
      'Large text, patient video lectures & personalized Salem tutor support',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Safe Digital World & Banking',
        lessons: ['Recognizing Phishing Calls & Fake SMS Alerts', 'Safe UPI Payments & Banking Apps Setup', 'Protecting Passwords & Device Privacy'],
        quizzesCount: 8,
      },
      {
        moduleTitle: 'Module 2: Cognitive Fitness & Memory Games',
        lessons: ['Word Associations & Memory Retention Exercises', 'Lateral Thinking & Pattern Recognition', 'Mindfulness, Focus & Daily Mental Agility'],
        quizzesCount: 8,
      },
    ],
  },
  {
    id: 'course-history-gk',
    title: 'Comprehensive Indian & World History + Static GK',
    exam: 'HIST-GK',
    category: 'History_GK',
    level: 'Intermediate',
    instructor: {
      name: 'Dr. Meenakshi Sundaresan',
      role: 'Historian & Competitive Civil Exam Resource Specialist',
      avatar: './assets/images/img-1573497019940-1c.webp',
      rating: 4.95,
    },
    rating: 4.95,
    reviewsCount: 3450,
    enrolledStudents: 21800,
    durationWeeks: 10,
    videoHours: 65,
    practiceQuestions: 3600,
    fullMocksCount: 14,
    originalPrice: 169,
    salePrice: 99,
    badge: 'High Yield',
    highlights: [
      'Ancient to Modern Indian History chronological timeline mindmaps',
      'World Geopolitics, UN Treaties & Global Revolutionary movements',
      'General Science, Space Missions & Current Affairs 2026 compendium',
      '14 Full-length timed mock tests with detailed historical source notes',
    ],
    syllabus: [
      {
        moduleTitle: 'Module 1: Indian History & Freedom Struggle',
        lessons: ['Indus Valley, Vedic Age & Mauryan Empire', 'Mughal Administration & South Indian Kingdoms', 'Revolt of 1857 to Indian Independence 1947'],
        quizzesCount: 12,
      },
      {
        moduleTitle: 'Module 2: Indian Constitution & General Knowledge',
        lessons: ['Preamble, Fundamental Rights & Directive Principles', 'Physical Geography of India & Major Rivers', 'Space Science, Awards & 2026 World Current Affairs'],
        quizzesCount: 12,
      },
    ],
  },
];

var FACULTY_MEMBERS = window.FACULTY_MEMBERS = [
  {
    id: 'fac-1',
    name: 'Dr. Julian Thorne',
    role: 'Lead Quantitative Scientist & Author',
    credentials: 'PhD Applied Mathematics, Harvard University',
    institution: 'Ex-ETS Advisory Consultant',
    specialization: 'Quant Reasoning, Probability Models, Adaptive IRT',
    studentsTrained: '45,000+',
    avgScore: '168/170',
    avatar: './assets/images/img-1534528741775-53.webp',
    bio: 'Pioneered rapid mental arithmetic techniques now utilized by thousands of 99th percentile test takers worldwide.',
    featuredExam: 'GRE & GMAT Quant',
  },
  {
    id: 'fac-2',
    name: 'Dr. Marcus Vance, MD',
    role: 'Medical Board Director & Clinical Educator',
    credentials: 'MD Johns Hopkins, Top 0.1% National Score',
    institution: 'Johns Hopkins School of Medicine',
    specialization: 'Organ Systems, Biochemical Pathways, Vignette Reasoning',
    studentsTrained: '28,000+',
    avgScore: '522/528',
    avatar: './assets/images/img-1537368910025-70.webp',
    bio: 'Author of three premier medical prep textbooks and mentor to thousands of matriculated medical students across the US and UK.',
    featuredExam: 'MCAT & USMLE Step 1',
  },
  {
    id: 'fac-3',
    name: 'Elena Rostova, MBA',
    role: 'Executive Director of Business School Prep',
    credentials: 'MBA Wharton School of Business, GMAT 770',
    institution: 'Former Admissions Committee Evaluator',
    specialization: 'Data Insights, Executive Logic, Critical Reasoning',
    studentsTrained: '32,000+',
    avgScore: '725/805',
    avatar: './assets/images/img-1573496359142-b8.webp',
    bio: 'Specializes in deconstructing standardized business exam algorithms to eliminate test day cognitive fatigue.',
    featuredExam: 'GMAT Focus Edition',
  },
  {
    id: 'fac-4',
    name: 'Claire Kensington',
    role: 'Undergraduate Admissions Test Specialist',
    credentials: 'BA English & Math, Stanford University',
    institution: 'National Merit Scholar Mentor',
    specialization: 'Adaptive Digital SAT, Desmos Geometry, Reading Rhetoric',
    studentsTrained: '52,000+',
    avgScore: '1540/1600',
    avatar: './assets/images/img-1580489944761-15.webp',
    bio: 'Has guided over 1,200 high schoolers to Ivy League, MIT, and Stanford acceptances through targeted adaptive preparation.',
    featuredExam: 'Digital SAT & ACT',
  },
];

var TESTIMONIALS = window.TESTIMONIALS = [
  {
    id: 'test-1',
    name: 'Priya Narayanan',
    exam: 'GRE General',
    score: '336 / 340',
    previousScore: '308',
    percentile: '99th Percentile',
    targetSchool: 'MIT',
    program: 'MS in Computational Science & Engineering',
    quote: 'The section-adaptive mock tests on AcroExam are identical to the actual exam day environment. Seeing my predicted percentile climb from 62% to 99% gave me unmatched composure.',
    avatar: './assets/images/img-1534528741775-53.webp',
    verified: true,
    year: '2025',
  },
  {
    id: 'test-2',
    name: 'Daniel Zhao',
    exam: 'GMAT Focus',
    score: '735 / 805',
    previousScore: '645',
    percentile: '99.5th Percentile',
    targetSchool: 'Stanford GSB',
    program: 'Master of Business Administration (MBA)',
    quote: 'The Data Insights drills were absolute game changers. I learned how to process 3-tab reasoning questions in under 110 seconds without missing subtle traps.',
    avatar: './assets/images/img-1507003211169-0a.webp',
    verified: true,
    year: '2025',
  },
  {
    id: 'test-3',
    name: 'Maya Al-Mansoor',
    exam: 'MCAT',
    score: '524 / 528',
    previousScore: '506',
    percentile: '100th Percentile',
    targetSchool: 'Johns Hopkins',
    program: 'MD Program (Class of 2029)',
    quote: 'No other platform explains question rationales with this level of biochemical clarity. The passage drill mode trained my brain to read research figures at lightning speed.',
    avatar: './assets/images/img-1517841905240-47.webp',
    verified: true,
    year: '2025',
  },
  {
    id: 'test-4',
    name: 'Ethan Ross',
    exam: 'Digital SAT',
    score: '1570 / 1600',
    previousScore: '1310',
    percentile: '99th+ Percentile',
    targetSchool: 'Columbia University',
    program: 'Economics & Mathematics',
    quote: 'Mastering the Desmos hacks alone gained me at least 90 points in Math Module 2. The practice interface is even smoother than College Board Bluebook.',
    avatar: './assets/images/img-1539571696357-5a.webp',
    verified: true,
    year: '2025',
  },
  {
    id: 'test-5',
    name: 'Aisha Siddiqui',
    exam: 'USMLE Step 1',
    score: 'Pass (High Score Margin)',
    previousScore: 'Diagnostic Fail',
    percentile: 'Top Decile',
    targetSchool: 'Mayo Clinic',
    program: 'Internal Medicine Residency Match',
    quote: 'The clinical vignette test engine helped me spot the exact pathophysiology path within seconds of reading each stem. Truly indispensable medical preparation.',
    avatar: './assets/images/img-1573497019940-1c.webp',
    verified: true,
    year: '2024',
  },
  {
    id: 'test-6',
    name: 'Rohan Verma',
    exam: 'GATE CS',
    score: 'AIR 42',
    previousScore: 'AIR 2800',
    percentile: '99.9th Percentile',
    targetSchool: 'IISc Bangalore',
    program: 'M.Tech in Artificial Intelligence',
    quote: 'The numerical answer type tests and compiler design drills directly matched the official exam difficulty. AcroExam gave me the exact rigor required for a double-digit rank.',
    avatar: './assets/images/img-1500648767791-00.webp',
    verified: true,
    year: '2025',
  },
];

var MOCK_QUESTIONS = window.MOCK_QUESTIONS = [
  {
    id: 1,
    exam: 'GRE General',
    section: 'Quantitative Reasoning',
    difficulty: 'Hard',
    question: 'If integer x is selected at random from the set of all two-digit positive integers that are multiples of 3, what is the probability that x is also a multiple of 4 or 5?',
    options: [
      '11 / 30',
      '13 / 30',
      '7 / 15',
      '1 / 2',
      '17 / 30',
    ],
    correctAnswer: 1, // 13/30
    explanation: 'Two-digit positive integers range from 10 to 99 (total 90 numbers). Multiples of 3 are 12, 15, ..., 99. The count is (99 - 12)/3 + 1 = 30 integers. For x to be a multiple of 4, it must be a multiple of lcm(3,4)=12: {12, 24, 36, 48, 60, 72, 84, 96} = 8 integers. For x to be a multiple of 5, it must be a multiple of lcm(3,5)=15: {15, 30, 45, 60, 75, 90} = 6 integers. Intersection is multiple of lcm(3,4,5)=60: {60} = 1 integer. By Principle of Inclusion-Exclusion, total favorable = 8 + 6 - 1 = 13 integers. Hence, probability = 13 / 30.',
    tip: 'Always apply Principle of Inclusion-Exclusion: |A ∪ B| = |A| + |B| - |A ∩ B| when counting overlapping sets on standardized quant.',
  },
  {
    id: 2,
    exam: 'GMAT Focus',
    section: 'Critical Reasoning',
    difficulty: 'Hard',
    question: 'Economist: "A country that subsidizes green renewable infrastructure will inevitably reduce domestic fossil fuel consumption. However, because international fossil fuel prices drop result of lower local demand, foreign consumption surges, canceling out global emission reductions." Which of the following, if true, most seriously weakens the economist’s argument?',
    options: [
      'Foreign nations that produce fossil fuels also impose strict internal energy tariffs.',
      'Renewable technology patents developed through domestic subsidies are rapidly adopted abroad, making clean energy cheaper than fossil fuels globally.',
      'Domestic consumption of fossil fuels accounts for less than 8 percent of global oil extraction.',
      'The subsidies require substantial taxpayer capital that could otherwise fund public transportation.',
      'Heavy freight transport relies on diesel engines that cannot currently operate on battery power alone.',
    ],
    correctAnswer: 1, // Option B weakens
    explanation: 'The economist assumes that domestic subsidies only lower international fossil fuel prices without creating alternative clean energy adoption abroad. Option B states that subsidized renewable technology patents are adopted internationally and become cheaper than fossil fuels globally, preventing the surge in foreign fossil fuel consumption and thus directly neutralizing the economist’s rebuttal.',
    tip: 'Look for assumptions that isolate the domestic market while ignoring global technology spillover effects.',
  },
  {
    id: 3,
    exam: 'MCAT Medical',
    section: 'Biological Foundations',
    difficulty: 'Medium',
    question: 'A competitive inhibitor is introduced into an enzymatic reaction catalyzed by hexokinase. Which of the following changes will be observed on a Lineweaver-Burk double-reciprocal plot?',
    options: [
      'The y-intercept increases while the x-intercept remains constant.',
      'The y-intercept remains constant while the x-intercept shifts closer to the origin.',
      'Both the x-intercept and y-intercept increase proportionally.',
      'The slope decreases while the y-intercept shifts down.',
    ],
    correctAnswer: 1, // Option B
    explanation: 'In competitive inhibition, the inhibitor binds reversibly to the active site, competing directly with the substrate. As a result, Vmax remains unchanged (so the y-intercept 1/Vmax remains constant), while the apparent Km increases. On a Lineweaver-Burk plot, the x-intercept is -1/Km. As Km increases, the magnitude 1/Km decreases, shifting the negative x-intercept closer to the origin (less negative).',
    tip: 'Remember: Competitive = Crosses at y-axis (same 1/Vmax). Non-competitive = Never touches at same Km (same x-intercept).',
  },
  {
    id: 4,
    exam: 'Digital SAT',
    section: 'Advanced Math',
    difficulty: 'Hard',
    question: 'The equation x² - kx + (k + 15) = 0 has exactly one real solution for x. If k is a positive constant, what is the value of k?',
    options: [
      '6',
      '8',
      '10',
      '12',
      '14',
    ],
    correctAnswer: 2, // 10
    explanation: 'For a quadratic equation ax² + bx + c = 0 to have exactly one real solution, the discriminant Δ = b² - 4ac must equal 0. Here a = 1, b = -k, c = (k + 15). Δ = (-k)² - 4(1)(k + 15) = k² - 4k - 60 = 0. Factoring: (k - 10)(k + 6) = 0. Since k is given positive constant, k = 10.',
    tip: 'Whenever a question mentions "exactly one real solution" or "tangent to the x-axis", immediately set Discriminant b² - 4ac = 0.',
  },
  {
    id: 5,
    exam: 'USMLE Step 1',
    section: 'Clinical Vignette',
    difficulty: 'Hard',
    question: 'A 48-year-old male with a history of hypertension presents with severe retrosternal chest pain radiating to his interscapular region. Transesophageal echocardiography reveals an intimal flap in the descending thoracic aorta distal to the origin of the left subclavian artery. Which of the following is the most appropriate initial medical management?',
    options: [
      'Immediate intravenous sodium nitroprusside alone',
      'Immediate intravenous esmolol or labetalol beta-blocker therapy',
      'Immediate emergent surgical repair with endovascular stent grafting',
      'Sublingual nitroglycerin and intravenous heparin bolus',
    ],
    correctAnswer: 1, // Beta blocker first
    explanation: 'The patient has a Stanford Type B aortic dissection (involving the descending aorta distal to the left subclavian artery). Initial medical therapy aims to reduce blood pressure and shearing forces (dP/dt). Intravenous beta-blockers (such or labetalol) must ALWAYS be initiated BEFORE any vasodilators (like nitroprusside) to prevent reflex tachycardia, which increases aortic wall shear stress.',
    tip: 'Dissection Rule: Always beta-block before vasodilating. Never give pure vasodilators first due to reflex sympathetic surge!',
  },
  {
    id: 6,
    exam: 'AI & Machine Learning',
    category: 'AI_ML',
    section: 'Deep Learning & Transformer Systems',
    difficulty: 'Hard',
    question: 'In standard Multi-Head Self-Attention (as formulated in Vaswani et al.), what is the asymptotic computational and memory complexity with respect to the input sequence length N for computing the attention score matrix (Q · Kᵀ)?',
    options: [
      'O(N) linear complexity',
      'O(N · log N) log-linear complexity',
      'O(N²) quadratic complexity',
      'O(N³) cubic complexity',
    ],
    correctAnswer: 2, // O(N^2)
    explanation: 'Computing the raw attention score matrix requires multiplying the Query matrix Q of shape (N, d_k) with the transposed Key matrix Kᵀ of shape (d_k, N), resulting in an (N × N) matrix. This matrix multiplication involves O(N² · d_k) operations and requires storing an N × N attention map in memory, giving O(N²) quadratic scaling with sequence length N.',
    tip: 'FlashAttention and KV Caching optimize memory bandwidth and inference token latency, but standard full self-attention scales quadratically O(N²).',
  },
  {
    id: 7,
    exam: 'Programming & Full Stack',
    category: 'Programming',
    section: 'Data Structures & Web Runtimes',
    difficulty: 'Medium',
    question: 'Consider the following JavaScript code snippet running in a modern browser environment. In what exact order will the numbers be logged to the console?',
    codeSnippet: `console.log(1);
setTimeout(() => console.log(2), 0);
Promise.resolve().then(() => console.log(3));
console.log(4);`,
    options: [
      '1, 2, 3, 4',
      '1, 4, 3, 2',
      '1, 4, 2, 3',
      '1, 3, 4, 2',
    ],
    correctAnswer: 1, // 1, 4, 3, 2
    explanation: '1 and 4 are synchronous statements executed immediately on the call stack. The Promise resolution attaches a callback to the Microtask Queue, while setTimeout(..., 0) posts a callback to the Macrotask (Task) Queue. The JavaScript Event Loop processes all microtasks before yielding to macrotasks. Therefore: 1, 4 (sync) -> 3 (microtask) -> 2 (macrotask).',
    tip: 'Microtasks (Promises, queueMicrotask, MutationObserver) always execute before Macrotasks (setTimeout, setInterval, I/O) in the Event Loop.',
  },
  {
    id: 8,
    exam: 'TNPSC Group 1, 2 & 4',
    category: 'TNPSC',
    section: 'Tamil Nadu Administration & History',
    difficulty: 'Medium',
    question: 'The famous Salem Steel Plant (SSP), a unit of Steel Authority of India Limited (SAIL), was established to exploit the rich magnetite iron ore reserves primarily found in which hill region of Salem district?',
    options: [
      'Shevaroy Hills (Yercaud)',
      'Kanjamalai Hills',
      'Kalrayan Hills',
      'Kolli Hills',
    ],
    correctAnswer: 1, // Kanjamalai Hills
    explanation: 'The Salem Steel Plant (SSP) in Salem, Tamil Nadu, was founded to leverage the rich magnetite iron ore deposits of the Kanjamalai Hills located just 14 km west of Salem city. It is globally renowned for manufacturing world-class austenitic and ferritic grade cold-rolled stainless steel.',
    tip: 'Salem is known as "Steel City" and "Mango City". Remember: Kanjamalai = Iron Ore / Steel; Shevaroy = Bauxite & Coffee / Yercaud; Kolli Hills = Medicinal plants.',
  },
  {
    id: 9,
    exam: 'Indian Railways (RRB)',
    category: 'Railways',
    section: 'Speed, Time & Distance Arithmetic',
    difficulty: 'Easy',
    question: 'A passenger express train 180 meters in length is traveling at a uniform speed of 72 km/h. How many seconds will it take to completely pass a station platform that is 220 meters long?',
    options: [
      '15 seconds',
      '20 seconds',
      '25 seconds',
      '28 seconds',
    ],
    correctAnswer: 1, // 20 seconds
    explanation: 'Total distance to be covered to clear the platform = Length of train + Length of platform = 180 m + 220 m = 400 m. Convert train speed from km/h to m/s: 72 × (5 / 18) = 20 m/s. Time = Distance / Speed = 400 m / 20 m/s = 20 seconds.',
    tip: 'Quick Unit Conversion for Railways CBT: Multiply km/h by 5/18 to get m/s. Multiply m/s by 18/5 to get km/h.',
  },
  {
    id: 10,
    exam: 'Banking (IBPS & SBI PO)',
    category: 'Banking',
    section: 'Monetary Policy & Financial Awareness',
    difficulty: 'Medium',
    question: 'When the Reserve Bank of India (RBI) Monetary Policy Committee (MPC) raises the Policy Repo Rate by 25 basis points, what is the immediate expected primary effect on commercial banking liquidity and lending rates?',
    options: [
      'Commercial banks can borrow from RBI at lower cost, leading to reduced home loan interest rates.',
      'The cost of short-term borrowing for banks from RBI rises, incentivizing banks to increase lending and deposit interest rates.',
      'The Cash Reserve Ratio (CRR) automatically drops to zero across all scheduled public sector banks.',
      'Foreign institutional investor (FII) equity inflows decrease immediately without affecting credit markets.',
    ],
    correctAnswer: 1, // Option B
    explanation: 'Repo Rate is the benchmark rate at which the RBI lends short-term funds to commercial banks against government securities. An increase in the Repo Rate increases the cost of capital for commercial banks, which promptly passes through lending rates (MCLR/EBLR) to borrowers and higher deposit yields, curbing excess liquidity to control inflation.',
    tip: 'Repo Rate hike = Tight Monetary Policy (fights inflation, dampens liquidity). Reverse Repo = Rate at which RBI absorbs surplus liquidity from banks.',
  },
  {
    id: 11,
    exam: 'History & General Knowledge',
    category: 'History_GK',
    section: 'Indian Freedom Movement & Polity',
    difficulty: 'Easy',
    question: 'Who served Chairman of the Drafting Committee of the Constituent Assembly of India, which formulated the Constitution adopted on 26th November 1949?',
    options: [
      'Dr. Rajendra Prasad',
      'Pandit Jawaharlal Nehru',
      'Dr. B.R. Ambedkar',
      'Sardar Vallabhbhai Patel',
    ],
    correctAnswer: 2, // Dr. B.R. Ambedkar
    explanation: 'Dr. B.R. Ambedkar was appointed Chairman of the Drafting Committee set up on 29 August 1947 by the Constituent Assembly. Under his legal and constitutional leadership, the final draft of the Indian Constitution was formulated and formally adopted on 26 November 1949 (celebrated Constitution Day).',
    tip: 'Distinction to remember: Dr. Rajendra Prasad was President of the Constituent Assembly, whereas Dr. B.R. Ambedkar was Chairman of the Drafting Committee.',
  },
  {
    id: 12,
    exam: 'Kids & Junior Olympiad',
    category: 'Kids',
    section: 'Fun Math & Space Science',
    difficulty: 'Easy',
    question: 'In our solar system, which planet is famously nicknamed the "Red Planet" because the iron oxide mineral rust on its rocky surface gives it a reddish glow?',
    options: [
      'Venus',
      'Mars',
      'Jupiter',
      'Mercury',
    ],
    correctAnswer: 1, // Mars
    explanation: 'Mars is known "Red Planet" because its soil contains iron oxide (rust), making the rocks, dust, and thin atmosphere appear reddish-orange to telescopes from Earth!',
    tip: 'Mars has two small potato-shaped moons called Phobos and Deimos, and the largest volcano in the solar system, Olympus Mons!',
  },
  {
    id: 13,
    exam: 'Senior Citizens & Lifelong Learning',
    category: 'Senior',
    section: 'Safe Digital Banking & Fraud Prevention',
    difficulty: 'Easy',
    question: 'You receive an urgent phone call claiming to be from your pension branch or bank manager, stating that your bank account will be blocked within 30 minutes unless you read out the 6-digit OTP just sent to your phone. What is the correct and safest action to take?',
    options: [
      'Read out the 6-digit OTP immediately to avoid having your pension account blocked.',
      'Never share the OTP or bank credentials with anyone under any circumstances; disconnect the call and contact your local bank branch directly.',
      'Share only the last 3 digits of the OTP to verify your identity partially.',
      'Ask the caller for their staff ID badge number and then give them your internet banking password.',
    ],
    correctAnswer: 1, // Option B
    explanation: 'Legitimate banks, government pension offices, and RBI officials NEVER ask for your OTP, PIN, CVV, or passwords over phone calls, SMS, or email. Any caller demanding an OTP under urgency or threat of account suspension is an imposter conducting a cyber fraud attack. Immediately hang up and report to the cybercrime helpline (1930 in India).',
    tip: 'Golden Rule of Digital Safety: OTP means "One-Time Password" for YOU alone. Sharing an OTP gives the fraudster authorization to transfer your money.',
  },
];

var PRICING_PLANS = window.PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter Practice Pass',
    priceMonthly: 39,
    priceAnnual: 29,
    period: 'per month',
    description: 'Essential toolkit for candidates starting initial diagnostics and topic-level drills.',
    features: [
      'Access to 2,500+ practice questions',
      '3 Full-length adaptive mock exams',
      'Detailed answer keys & basic explanations',
      'Standard progress & accuracy tracking',
      'Community discussion forum access',
      'Mobile web app accessibility',
    ],
    ctaText: 'Start with Starter',
  },
  {
    id: 'pro',
    name: 'Pro Scholar Pack',
    priceMonthly: 79,
    priceAnnual: 59,
    period: 'per month',
    description: 'Our most popular comprehensive preparation suite with AI diagnostics and faculty sessions.',
    isPopular: true,
    badge: 'Most Popular',
    features: [
      'Unlimited access to 15,000+ question bank',
      '15 Full-length proctored adaptive mock exams',
      'AI-powered IRT diagnostic & score predictor',
      'Video solutions for all high-difficulty items',
      'Weekly live doubt resolution workshops',
      'Guaranteed score boost (+12 pts or refund)',
      'Offline downloadable formula & vocabulary sheets',
    ],
    ctaText: 'Get Pro Scholar Pass',
  },
  {
    id: 'elite',
    name: 'All-Access Elite Immersion',
    priceMonthly: 149,
    priceAnnual: 119,
    period: 'per month',
    description: '1-on-1 personalized mentorship with Ivy League instructors and unlimited mock evaluations.',
    badge: '1-on-1 Mentorship',
    features: [
      'All Pro Scholar features included',
      'Unlimited proctored full-length mocks',
      'Monthly 1-on-1 strategy sessions with PhD mentors',
      'Customized daily adaptive study roadmap',
      'Priority 15-minute doubt turnaround desk',
      'Admissions essay & interview preparation guide',
      'Lifetime archive access to recorded masterclasses',
    ],
    ctaText: 'Enroll in Elite',
  },
];

var PREP_CENTERS = window.PREP_CENTERS = [
  {
    id: 'center-salem',
    city: 'Salem, Tamil Nadu (HQ)',
    country: 'India',
    address: 'Stackly Tech Park, #42 Innovation Corridor, Meyyanur Bypass Road, Salem, Tamil Nadu 636004, India',
    phone: '+91 (427) 244-8890 / +91 98427 12345',
    email: 'salem.hq@stackly.in',
    hours: 'Mon - Sat: 8:00 AM - 9:30 PM | Sun: 9:00 AM - 7:00 PM',
    facilities: ['Proctored CBT Simulation Arena', 'Stackly Innovation & AI Research Lab', 'Faculty Doubts & Mentorship Studio', '1-on-1 Admissions Guidance Suite'],
    image: './assets/images/img-1497366216548-37.webp',
  },
  {
    id: 'center-boston',
    city: 'Boston, Massachusetts',
    country: 'United States',
    address: '424 Cambridge St, Tech Innovation Square, Boston, MA 02138',
    phone: '+1 (617) 555-0192',
    email: 'boston@stackly.in',
    hours: 'Mon - Sat: 8:00 AM - 9:00 PM | Sun: 9:00 AM - 6:00 PM',
    facilities: ['Proctored Mock Testing Lab', 'Quiet Study Pods', 'Live Faculty Doubts Desk', '1-on-1 Counseling Suites'],
    image: './assets/images/img-1541339907198-e0.webp',
  },
  {
    id: 'center-london',
    city: 'London, United Kingdom',
    country: 'United Kingdom',
    address: '18 Bloomsbury Square, Holborn, London WC1A 2NS',
    phone: '+44 20 7946 0842',
    email: 'london@stackly.in',
    hours: 'Mon - Fri: 8:30 AM - 8:30 PM | Sat - Sun: 10:00 AM - 5:00 PM',
    facilities: ['High-Speed Computer Lab', 'IELTS Speaking Simulation Rooms', 'Medical Anatomy Models', 'Executive Lounge'],
    image: './assets/images/img-1513635269975-59.webp',
  },
  {
    id: 'center-singapore',
    city: 'Singapore',
    country: 'Singapore',
    address: '79 Anson Road #14-02, Tanjong Pagar, Singapore 079906',
    phone: '+65 6789 2341',
    email: 'singapore@stackly.in',
    hours: 'Mon - Sun: 8:00 AM - 10:00 PM',
    facilities: ['24/7 Digital Testing Arena', 'Private Mentor Cubicles', 'High-Yield Audio Library', 'Cafeteria & Discussion Pods'],
    image: './assets/images/img-1525625293386-3f.webp',
  },
  {
    id: 'center-newyork',
    city: 'New York, New York',
    country: 'United States',
    address: '575 Fifth Avenue, 18th Floor, New York, NY 10017',
    phone: '+1 (212) 555-0814',
    email: 'nyc@stackly.in',
    hours: 'Mon - Sat: 8:00 AM - 9:30 PM | Sun: 10:00 AM - 6:00 PM',
    facilities: ['Standardized Testing Simulators', 'Bar & Law Exam Seminar Hall', 'Ivy Admissions Consultation Office'],
    image: './assets/images/img-1496868834840-5f.webp',
  },
];

var SALEM_COMPANY_INFO = window.SALEM_COMPANY_INFO = {
  companyName: 'Salem Stackly Technologies Private Limited',
  brandName: 'Stackly',
  tagline: 'Premium Online Exam Preparation & Psychometric Systems',
  headquarters: 'Salem, Tamil Nadu, India',
  fullAddress: 'Stackly Tech Park, #42 Innovation Corridor, Meyyanur Bypass Road, Fairlands, Salem, Tamil Nadu 636004, India',
  phone: '+91 (427) 244-8890',
  emergencyPhone: '+91 98427 12345',
  email: 'contact@stackly.in',
  admissionsEmail: 'admissions.salem@stackly.in',
  careersEmail: 'careers@stackly.in',
  hours: 'Mon - Sat: 8:00 AM - 9:30 PM | Sun: 9:00 AM - 7:00 PM IST',
  registrationId: 'U72900TZ2021PTC035412',
  cin: 'L74999TZ2020PTC049102',
  pan: 'AABCS9821K',
  gstin: '33AABCS9821K1Z5',
  foundedYear: '2021',
  managingDirector: 'Dr. R. Selvakumar, M.Tech, Ph.D.',
  academicDirector: 'Prof. Ananya Sundaram, M.Sc (EdTech)',
};

var FAQS = window.FAQS = [
  {
    id: 'faq-1',
    category: 'mocks',
    question: 'How realistic are your mock tests compared to the actual exam?',
    answer: 'Our mock test interfaces replicate the exact UI, font size, button behaviors, section timing, and built-in calculators (such for Digital SAT or ETS calculator for GRE) of official test administration bodies. Furthermore, our scoring algorithms employ Item Response Theory (IRT) to recalibrate question difficulty in real time based on your performance.',
  },
  {
    id: 'faq-2',
    category: 'general',
    question: 'Can I practice on mobile phones or tablets?',
    answer: 'Yes! AcroExam is fully responsive across smartphones, tablets, laptops, and ultra-wide desktop monitors. You can solve daily practice challenges, review flashcards, and watch HD video lectures on mobile. However, for full-length 3+ hour mock exams, we recommend a desktop or laptop to replicate exam room conditions.',
  },
  {
    id: 'faq-3',
    category: 'courses',
    question: 'How do live doubt resolution sessions work?',
    answer: 'Enrolled students can submit questions 24/7 via the Doubt Portal with screenshot uploads. Top questions are reviewed in our weekly live office hours with master faculty. Pro and Elite scholars also have direct access to 1-on-1 doubt clearing desks with guaranteed sub-15 minute turnaround times.',
  },
  {
    id: 'faq-4',
    category: 'billing',
    question: 'What is your Score Improvement Guarantee policy?',
    answer: 'We guarantee a measurable score improvement (e.g. +12 points on GRE, +80 on GMAT, or +150 on SAT) if you complete at least 80% of video lessons and 8 proctored full-length mocks. If your official score does not improve over your baseline, we provide a 100% full tuition refund or 6 months of free unlimited extension.',
  },
  {
    id: 'faq-5',
    category: 'general',
    question: 'Are study notes and formula cheat sheets downloadable?',
    answer: 'Yes! All formula sheets, high-yield summary cheat sheets, and vocabulary flashcard decks can be viewed online or downloaded high-resolution PDF files for offline revision.',
  },
];

var HIGH_YIELD_RESOURCES = window.HIGH_YIELD_RESOURCES = [
  {
    id: 'res-1',
    title: 'GRE Quant 100 Golden Formulas & Shortcuts',
    exam: 'GRE',
    format: 'PDF Cheat Sheet (14 Pages)',
    downloads: '84,000+',
    rating: 4.95,
    description: 'Geometry derivations, prime factorization rules, and rate/work speed multipliers.',
  },
  {
    id: 'res-2',
    title: 'Digital SAT Desmos Calculator Mastery Handbook',
    exam: 'SAT',
    format: 'Interactive Guide (22 Pages)',
    downloads: '112,000+',
    rating: 4.98,
    description: 'Step-by-step slider tricks and regression models to solve Module 2 math in 15 seconds.',
  },
  {
    id: 'res-3',
    title: 'MCAT High-Yield Metabolic Pathways Matrix',
    exam: 'MCAT',
    format: 'Full Color Poster & Summary',
    downloads: '46,000+',
    rating: 4.94,
    description: 'Glycolysis, Krebs Cycle, Gluconeogenesis, and rate-limiting enzymes cross-referenced.',
  },
  {
    id: 'res-4',
    title: 'GMAT Focus Critical Reasoning Logical Fallacies Deck',
    exam: 'GMAT',
    format: 'Flashcard Digest (35 Scenarios)',
    downloads: '68,000+',
    rating: 4.92,
    description: 'Deconstruct correlation vs causation, scope shifts, and sampling bias in business passages.',
  },
];

var STUDENT_DASHBOARD_DATA = window.STUDENT_DASHBOARD_DATA = {
  profile: {
    name: 'Alex Mercer',
    email: 'alex.mercer@stanford.edu',
    targetExam: 'GRE General Test',
    targetScore: '335+ / 340',
    currentEstimate: '331 / 340',
    examDate: 'November 18, 2026',
    streak: 19,
    xp: 4850,
    readinessPercentage: 86,
    completedMocks: 7,
    accuracyRate: 88.4,
    avgTimePerQuestion: '1m 18s',
  },
  enrolledCourses: [
    {
      id: 'course-gre-mastery',
      title: 'GRE General 335+ Masterclass with Live Mocks',
      instructor: 'Dr. Julian Thorne',
      progress: 68,
      totalHours: 72,
      completedHours: 49,
      nextLesson: 'Module 5: Advanced Triangle Geometry & Coordinate Plane Traps',
      lastActive: 'Today, 2 hours ago',
      thumbnail: './assets/images/img-1434030216411-0b.webp',
    },
    {
      id: 'course-gmat-elite',
      title: 'GMAT Focus 705+ Comprehensive Bootcamp',
      instructor: 'Marcus Sterling, MBA',
      progress: 32,
      totalHours: 64,
      completedHours: 20.5,
      nextLesson: 'Module 3: Multi-Source Reasoning Data Sets & Graph Synthesis',
      lastActive: 'Yesterday',
      thumbnail: './assets/images/img-1454165804606-c3.webp',
    },
  ],
  recentMockHistory: [
    {
      id: 'mock-104',
      title: 'Full-Length Adaptive Diagnostic Mock #4',
      date: 'Sept 01, 2026',
      score: '332 / 340',
      quantScore: '168 / 170',
      verbalScore: '164 / 170',
      percentile: '96th %ile',
      duration: '3h 12m',
      status: 'Completed',
    },
    {
      id: 'mock-103',
      title: 'Quant Advanced Sectional Gauntlet',
      date: 'Aug 26, 2026',
      score: '169 / 170',
      quantScore: '169 / 170',
      verbalScore: '—',
      percentile: '98th %ile',
      duration: '42m',
      status: 'Completed',
    },
    {
      id: 'mock-102',
      title: 'Verbal Text Completion & RC Speed Trial',
      date: 'Aug 21, 2026',
      score: '162 / 170',
      quantScore: '—',
      verbalScore: '162 / 170',
      percentile: '91st %ile',
      duration: '35m',
      status: 'Completed',
    },
  ],
  errorLogItems: [
    {
      id: 'err-1',
      question: 'A circle of radius r is inscribed in a square of side length s...',
      topic: 'Geometry - Circles & Polygons',
      errorType: 'Rushed Reading / Misread condition',
      difficulty: 'Hard',
      dateAdded: 'Yesterday',
      resolved: false,
    },
    {
      id: 'err-2',
      question: 'Although the author claims the artifact was forged, subsequent carbon-14 tests...',
      topic: 'Sentence Equivalence - Dual Shift',
      errorType: 'Vocabulary Nuance (Ambiguous vs Equivocal)',
      difficulty: 'Hard',
      dateAdded: '3 days ago',
      resolved: true,
    },
    {
      id: 'err-3',
      question: 'If x and y are positive integers such that 3x + 7y = 100...',
      topic: 'Number Theory - Diophantine Constraints',
      errorType: 'Overlooked integer constraint',
      difficulty: 'Medium',
      dateAdded: '5 days ago',
      resolved: true,
    },
  ],
  upcomingEvents: [
    {
      id: 'ev-1',
      title: 'Live 1-on-1 Strategy Review with Dr. Julian Thorne',
      type: 'Mentor Session',
      time: 'Tomorrow, 4:00 PM IST',
      platform: 'Stackly Video Portal (Salem Server)',
      mentor: 'Dr. Julian Thorne',
    },
    {
      id: 'ev-2',
      title: 'National Proctored Mock Test #5 (All-India & Global Rank)',
      type: 'Official Mock',
      time: 'Saturday, 10:00 AM IST',
      platform: 'Proctored Browser Required',
      mentor: 'Automated IRT Proctor',
    },
  ],
};

var ADMIN_DASHBOARD_DATA = window.ADMIN_DASHBOARD_DATA = {
  kpis: {
    totalStudents: 148520,
    activeExamsToday: 3412,
    totalQuestions: 26840,
    platformRevenue: '$482,900',
    avgAccuracyPercent: 78.4,
    questionsAnsweredToday: 624500,
  },
  liveExams: [
    {
      sessionId: 'SES-8921',
      studentName: 'Priya Sundaram',
      exam: 'GRE General',
      timeElapsed: '1h 24m / 3h 45m',
      currentSection: 'Section 3: Quant Hard Tier',
      questionsDone: '38 / 60',
      antiCheatStatus: 'Normal (Clean)',
      ipLocation: 'Chennai, India',
    },
    {
      sessionId: 'SES-8922',
      studentName: 'Ethan Reynolds',
      exam: 'Digital SAT',
      timeElapsed: '48m / 2h 14m',
      currentSection: 'Math Module 2 Advanced',
      questionsDone: '18 / 44',
      antiCheatStatus: 'Normal (Clean)',
      ipLocation: 'Chicago, USA',
    },
    {
      sessionId: 'SES-8923',
      studentName: 'Karthik Raja',
      exam: 'GATE CS',
      timeElapsed: '2h 10m / 3h 00m',
      currentSection: 'Algorithms & Data Structures',
      questionsDone: '46 / 65',
      antiCheatStatus: 'Focus Lost x1 (Recovered)',
      ipLocation: 'Salem, India',
    },
    {
      sessionId: 'SES-8924',
      studentName: 'Sophia Lin',
      exam: 'MCAT Medical',
      timeElapsed: '3h 40m / 7h 30m',
      currentSection: 'CARS Analysis',
      questionsDone: '62 / 120',
      antiCheatStatus: 'Normal (Clean)',
      ipLocation: 'Singapore',
    },
  ],
  questionBankSummary: [
    {
      id: 'QB-GRE-Q102',
      exam: 'GRE',
      topic: '3D Geometry Cylinders',
      difficulty: 'Hard (b=1.84)',
      discrimination: 'High (a=1.42)',
      accuracy: '42.8%',
      attempts: 14200,
      status: 'Active Calibrated',
    },
    {
      id: 'QB-SAT-M208',
      exam: 'SAT',
      topic: 'Quadratic Vertex Form',
      difficulty: 'Medium (b=0.45)',
      discrimination: 'Normal (a=1.10)',
      accuracy: '68.2%',
      attempts: 28400,
      status: 'Active Calibrated',
    },
    {
      id: 'QB-GMAT-DI44',
      exam: 'GMAT',
      topic: 'Multi-Source Tabular',
      difficulty: 'Hard (b=1.92)',
      discrimination: 'Very High (a=1.65)',
      accuracy: '36.5%',
      attempts: 8900,
      status: 'Active Calibrated',
    },
    {
      id: 'QB-MCAT-B119',
      exam: 'MCAT',
      topic: 'Enzyme Kinetics Michaelis-Menten',
      difficulty: 'Mastery (b=2.10)',
      discrimination: 'High (a=1.55)',
      accuracy: '31.2%',
      attempts: 11200,
      status: 'Active Calibrated',
    },
  ],
  studentRoster: [
    {
      id: 'STU-902',
      name: 'Alex Mercer',
      email: 'alex.mercer@stanford.edu',
      exam: 'GRE General',
      enrolledCourse: 'GRE 335+ Masterclass',
      diagnosticScore: '332 / 340',
      mocksTaken: 7,
      registeredDate: 'Aug 10, 2026',
      status: 'High Performer (Top 1%)',
    },
    {
      id: 'STU-903',
      name: 'Ananya Krishnan',
      email: 'ananya.k@iitm.ac.in',
      exam: 'GATE CS',
      enrolledCourse: 'GATE Tech Master Drills',
      diagnosticScore: '78.5 / 100',
      mocksTaken: 11,
      registeredDate: 'July 28, 2026',
      status: 'Top AIR Track',
    },
    {
      id: 'STU-904',
      name: 'David Zhao',
      email: 'dzhao@berkeley.edu',
      exam: 'Digital SAT',
      enrolledCourse: 'SAT 1550+ Pro Intensive',
      diagnosticScore: '1540 / 1600',
      mocksTaken: 9,
      registeredDate: 'Aug 04, 2026',
      status: 'Goal Achieved',
    },
    {
      id: 'STU-905',
      name: 'Rohan Verma',
      email: 'rohan.v@gmail.com',
      exam: 'GMAT Focus',
      enrolledCourse: 'GMAT 705+ Complete Pass',
      diagnosticScore: '685 / 805',
      mocksTaken: 4,
      registeredDate: 'Aug 18, 2026',
      status: 'Needs Quant Pacing Review',
    },
  ],
  systemNodes: [
    { name: 'Salem HQ Primary Cluster (Tamil Nadu)', status: 'Optimal (12ms ping)', load: '42%' },
    { name: 'Global IRT Calibration Service', status: 'Healthy', load: '38%' },
    { name: 'Proctored Video Anti-Cheat Stream', status: 'Active (3.4k streams)', load: '58%' },
    { name: 'Question Bank CDN (Edge)', status: 'Operational 99.99%', load: '24%' },
  ],
};

var COLOR_THEMES = window.COLOR_THEMES = [
  {
    id: 'royal',
    name: 'Electric Royal',
    tagline: 'Vibrant Royal Indigo, Electric Violet & Warm Amber',
    primaryColor: '#4F46E5',
    accentColor: '#F59E0B',
    gradient: 'from-indigo-600 via-purple-600 to-indigo-700',
    isDark: false,
  },
  {
    id: 'emerald',
    name: 'Emerald Prodigy',
    tagline: 'Deep Forest Jade, Mint Teal & Luminous Gold',
    primaryColor: '#059669',
    accentColor: '#D97706',
    gradient: 'from-emerald-600 via-teal-600 to-emerald-700',
    isDark: false,
  },
  {
    id: 'sunset',
    name: 'Sunset Coral',
    tagline: 'Radiant Coral Rose, Warm Tangerine & Ruby',
    primaryColor: '#E11D48',
    accentColor: '#F59E0B',
    gradient: 'from-rose-600 via-orange-500 to-amber-600',
    isDark: false,
  },
  {
    id: 'cyber',
    name: 'Midnight Cyber',
    tagline: 'Deep Obsidian Navy, Electric Neon Violet & Cyan Glow',
    primaryColor: '#6366F1',
    accentColor: '#06B6D4',
    gradient: 'from-indigo-900 via-slate-900 to-purple-950',
    isDark: true,
  },
];




var SERVICES_LIST = window.SERVICES_LIST = [
  {
    id: 'mock-labs',
    title: 'Adaptive Proctored Mock Test Labs',
    subtitle: 'High-fidelity simulation matching exact official exam interfaces and pressure',
    description:
      'Experience zero-surprise exam days. Our computer-based testing suites replicate exact test algorithms, item response theory (IRT) scoring, section-level time locks, and biometric proctoring for GRE, GMAT, TNPSC, UPSC, NEET, and Banking.',
    iconName: 'Laptop',
    category: 'Mock Labs',
    targetAudience: 'Candidates within 3 months of official test date seeking stamina and score calibration',
    highlights: [
      'Exact replica testing UI with official question delivery cadence',
      'Millisecond latency response-time tracking per question',
      'Real-time percentile ranking across 140,000+ active aspirants',
      'Instant AI post-exam error taxonomy with step-by-step video solutions',
    ],
    deliverables: [
      '60+ Full-length proctored simulations',
      'Adaptive sectional diagnostic tests',
      'Personalized mistake notebook & repeat-drill generation',
      'All-India percentile rank certificate',
    ],
    salemFacilityAccess: 'Unrestricted access to Salem HQ Air-conditioned CBT Computer Lab (8:00 AM – 10:00 PM)',
    recommendedDuration: '8 to 16 Weeks',
    pricingEstimate: '₹4,999 / quarter',
  },
  {
    id: 'one-on-one-mentorship',
    title: '1-on-1 Precision Cognitive Mentorship',
    subtitle: 'Dedicated 99th-percentile faculty mentoring to dismantle stubborn score plateaus',
    description:
      'When general lectures fail to raise your score past the 90th percentile, 1-on-1 cognitive coaching uncovers microscopic errors in problem-selection, elimination tactics, and anxiety pacing. Mentors meet weekly to review your question logs.',
    iconName: 'UserCheck',
    category: 'Mentorship',
    targetAudience: 'Aspirants stuck at score plateaus or needing customized accelerated preparation',
    highlights: [
      'Weekly 45-minute tactical video or in-person review at Salem HQ',
      'Cognitive flaw diagnosis: careless error vs. concept deficit vs. pacing panic',
      'Direct WhatsApp & phone hotline with lead educator',
      'Customized daily revision calendar synced to your work or college schedule',
    ],
    deliverables: [
      '12 Private 1-on-1 sessions per quarter',
      'Weekly customized problem sets targeting your bottom 3 weakest areas',
      'Quarterly psychological readiness and exam strategy audit',
      'Priority doubt clearance with guaranteed under-2-hour turnaround',
    ],
    salemFacilityAccess: 'Private acoustic study cabins at Stackly Salem Center with educator presence',
    recommendedDuration: '12 to 24 Weeks',
    pricingEstimate: '₹9,499 / quarter',
  },
  {
    id: 'hybrid-classroom',
    title: 'Salem HQ Hybrid Classroom & Studio Sessions',
    subtitle: 'Immersive live interactive lectures in Salem + crystal-clear 4K on-demand replay',
    description:
      'Join our flagship classroom batches in Fairlands, Salem, or livestream from anywhere in South India. Featuring dual-camera interactive smart boards, daily printed drill worksheets, and peer study study circles.',
    iconName: 'GraduationCap',
    category: 'Classroom',
    targetAudience: 'Freshers, final-year college students, and working professionals wanting structured daily routine',
    highlights: [
      'Morning (6:30 AM – 8:30 AM) & Evening (6:00 PM – 8:30 PM) flexible batches',
      'Comprehensive coverage from foundational arithmetic to advanced derivation',
      'Physical Salem classroom with ergonomic seating & high-speed Wi-Fi',
      'Instant access to 1,200+ hours of archived HD lecture recordings',
    ],
    deliverables: [
      '180 Hours of live instructional masterclasses',
      'Stackly Salem physical hardcopy book bundle (6 comprehensive volumes)',
      'Daily in-class speed tests and peer leaderboard',
      'Lifetime digital lecture archive access',
    ],
    salemFacilityAccess: 'Full campus access, library cubicles, and weekend intensive workshop auditoriums',
    recommendedDuration: '6 Months Comprehensive',
    pricingEstimate: '₹14,999 / course',
  },
  {
    id: 'predictive-analytics',
    title: 'Predictive Rank Analytics & Diagnostic Audits',
    subtitle: 'Machine-learning calibrated score forecasting using historical percentile distributions',
    description:
      'Stop guessing where you stand. Our neural model trained on over 2.4 million student question responses maps your diagnostic mock behavior against verified past cutoff marks for Tamil Nadu state services, IIMs, and US universities.',
    iconName: 'BarChart3',
    category: 'Analytics',
    targetAudience: 'Data-driven candidates seeking objective confidence before booking official exam dates',
    highlights: [
      'Projected score window accurate to ±2 points on GRE/GMAT and ±4 marks on TNPSC',
      'Category-wise cutoff readiness radar (e.g. BC/MBC/SC quota cutoffs mapped)',
      'Question difficulty discrimination curve (Item Characteristic Curve analysis)',
      'Time-decay retention tracking indicating when to review earlier topics',
    ],
    deliverables: [
      'Comprehensive 18-page Cognitive Diagnostic Audit report',
      'Benchmarking against the top 1% Salem cohort',
      'Readiness Index score with Green/Amber/Red official test date recommendation',
      'Exportable PDF scorecard for sponsor or university portfolio',
    ],
    salemFacilityAccess: 'In-person data consultation with Chief Psychometrics Officer at Salem Center',
    recommendedDuration: 'Continuous diagnostic monitoring',
    pricingEstimate: '₹2,499 / audit pack',
  },
  {
    id: 'interview-personality',
    title: 'Personality Board & Interview Simulation',
    subtitle: 'Mock panel interviews with retired IAS/IPS officers, PSU directors, and university deans',
    description:
      'Written exams get you to the threshold; personality tests secure your rank and preferred posting. Prepare with rigorous panel interviews that simulate the exact pressure, non-verbal posture, and rapid situational inquiry of official boards.',
    iconName: 'Award',
    category: 'Interview',
    targetAudience: 'Candidates qualified for TNPSC Group 1/2 Oral Test, UPSC Civil Services, Bank PO, and MBA admissions',
    highlights: [
      '3-Member expert panel with domain specialists and behavioral psychologists',
      'Multi-angle video recording with micro-expression and body language feedback',
      'Current affairs dossier focusing on Tamil Nadu governance, state budgets, and global trends',
      'DAF (Detailed Application Form) line-by-line cross-examination',
    ],
    deliverables: [
      '3 Full-length mock interview rounds with written evaluation score sheets',
      'Raw 4K video recording on USB drive for personal reflection',
      'Customized question bank generated from your personal academic background',
      'Spoken Tamil & English articulation refinement workshop',
    ],
    salemFacilityAccess: 'Salem Boardroom Suite (replica of TNPSC Chennai Oral Test chambers)',
    recommendedDuration: '3 to 5 Weeks post-written results',
    pricingEstimate: '₹6,999 / candidate',
  },
  {
    id: 'institutional-training',
    title: 'Collegiate & Institutional Career Acceleration',
    subtitle: 'On-campus placement training and competitive exam wings for colleges in Western Tamil Nadu',
    description:
      'Partnering with engineering, arts, and medical colleges across Salem, Namakkal, Erode, and Dharmapuri. We set up turnkey competitive exam cells with customized LMS portals, semester-aligned coaching, and faculty development.',
    iconName: 'Building',
    category: 'Institutional',
    targetAudience: 'Universities, colleges, autonomous institutions, and corporate training departments',
    highlights: [
      'Turnkey syllabus integration with college academic calendar',
      'White-labeled Stackly assessment engine for internal campus placements',
      'On-campus workshops by Salem HQ visiting faculty',
      'Institutional dashboard tracking student performance across departments',
    ],
    deliverables: [
      'Campus-wide diagnostic test with institutional ranking report',
      'Semester-long placement aptitude and reasoning modules',
      'Faculty orientation and question-crafting workshops',
      'Special discounted exam vouchers for enrolled students',
    ],
    salemFacilityAccess: 'Dedicated liaison desk and campus visits from Salem HQ coordinators',
    recommendedDuration: 'Semester / Annual MoU',
    pricingEstimate: 'Custom institutional proposal',
  },
];

var BLOG_POSTS = window.BLOG_POSTS = [
  {
    id: 'post-1',
    title: 'How to Clear TNPSC Group 1 Prelims 2026: The 120-Day Quantitative & General Studies Blueprint',
    slug: 'clear-tnpsc-group-1-prelims-120-day-blueprint',
    excerpt:
      'A structured day-by-day roadmap tailored for aspirants in Tamil Nadu. Master Samacheer Kalvi textbooks, Unit 8 & 9 state heritage, and mental ability without burning out.',
    category: 'TNPSC',
    readTime: '8 min read',
    publishedAt: 'September 2, 2026',
    author: {
      name: 'R. K. Sundaram',
      role: 'Head of TNPSC & Civil Services, Salem HQ',
      avatar: './assets/images/img-1507003211169-0a.webp',
    },
    tags: ['TNPSC Group 1', 'Unit 8 & 9', 'Samacheer Kalvi', 'Exam Strategy'],
    image: './assets/images/img-1434030216411-0b.webp',
    featured: true,
    content: [
      'The TNPSC Group 1 Preliminary Examination has evolved significantly over the past three cycles. Gone are the days when mere rote memorization of factual dates would secure a seat in the top bracket. The current question papers focus heavily on analytical synthesis, social-justice frameworks, and application of governance principles in Tamil Nadu.',
      'Unit 8 (History, Culture, Heritage and Socio-Political Movements in Tamil Nadu) and Unit 9 (Development Administration in Tamil Nadu) collectively account for over 60 to 70 questions in the 200-question paper. Treating these topics is the single biggest cause of prelims elimination.',
      'Phase 1 (Days 1–45): Thoroughly read 6th to 12th standard Samacheer Kalvi Social Science, History, and Political Science textbooks. Extract high-yield timelines of the Justice Party, Self-Respect Movement, and Dravidian welfare legislation.',
      'Phase 2 (Days 46–90): Daily 50-question sectional testing. Focus 90 minutes every morning on Aptitude & Mental Ability (25 questions). With 25/25 in Quant, your margin of safety in General Studies increases exponentially.',
      'Phase 3 (Days 91–120): Full-length proctored mocks at Salem CBT lab every Saturday. Analyze your negative-marking tolerance and fine-tune your test-day pacing strategy.',
    ],
  },
  {
    id: 'post-2',
    title: 'Top 7 Mental Math Shortcuts That Saved My GRE Quant Score from 158 to 169',
    slug: 'mental-math-shortcuts-gre-quant-score-jump',
    excerpt:
      'Eliminate calculator reliance on the GRE. Learn rapid estimation, digital roots, units-digit elimination, and weighted average balancing to save 12 minutes per section.',
    category: 'Aptitude',
    readTime: '6 min read',
    publishedAt: 'August 28, 2026',
    author: {
      name: 'Priya Narayanan',
      role: 'Senior Quantitative Specialist, Stackly Salem',
      avatar: './assets/images/img-1534528741775-53.webp',
    },
    tags: ['GRE General', 'Quantitative Reasoning', 'Mental Math', 'Score Boost'],
    image: './assets/images/img-1635070041078-e3.webp',
    featured: false,
    content: [
      'The on-screen GRE calculator is a seductive trap. While it guarantees accurate multiplication, mouse-clicking digits on an on-screen keypad consumes approximately 14 to 20 seconds per operation. Over a 20-question section, that amounts to 5 to 7 wasted minutes.',
      '1. The Seesaw Method for Weighted Averages: Instead of calculating (A*w1 + B*w2)/(w1+w2), visualize the distance between the two values on a number line. The ratio of quantities is inversely proportional to the ratio of distances from the average.',
      '2. Last Digit & Parity Filtering: When faced with massive exponent questions (e.g., units digit of 7^83), rely on cyclicity patterns (7, 9, 3, 1) rather than binomial expansion.',
      '3. Divisibility Rule of 7 and 13: Group digits in blocks of three from the right and alternately add and subtract. Test the resulting three-digit remainder in seconds.',
      '4. Estimation First: In Data Interpretation graphs, inspect the options before computing. If options are spread out by more than 10%, round aggressive numerators to clean 25s or 50s.',
    ],
  },
  {
    id: 'post-3',
    title: 'The Science of Spaced Repetition for 1,000+ GRE & GMAT Vocabulary Words',
    slug: 'spaced-repetition-vocabulary-mastery',
    excerpt:
      'Stop using 50-page alphabetical word lists. How cognitive retention curves and active recall flashcards ensure words stay in your long-term memory permanently.',
    category: 'Strategy',
    readTime: '7 min read',
    publishedAt: 'August 21, 2026',
    author: {
      name: 'Dr. Julian Thorne',
      role: 'Academic Director, Salem HQ',
      avatar: './assets/images/img-1472099645785-56.webp',
    },
    tags: ['Vocabulary', 'Flashcards', 'Cognitive Science', 'Verbal Reasoning'],
    image: './assets/images/img-1456513080510-7b.webp',
    featured: false,
    content: [
      'Hermann Ebbinghaus discovered the forgetting curve in 1885: within 48 hours of learning an isolated word, humans forget over 70% of the definition unless reinforced through active retrieval.',
      'Why alphabetical lists fail: When you study words starting with "Ab" (aberrant, abeyance, abhor, abjure), your brain experiences high retroactive interference. The words look identical and blend into cognitive fog.',
      'The Stackly 3-Tier Box Method: Divide vocabulary into thematic clusters (e.g., "Praise vs. Criticize", "Laconic vs. Loquacious", "Stubbornness"). Test yourself on day 1, day 3, day 7, and day 21.',
      'Contextual sentence framing: Never memorize isolated dictionary definitions. Always attach the word to a vivid emotional scenario or local memory landmark.',
    ],
  },
  {
    id: 'post-4',
    title: 'Salem Aspirant Spotlight: From College Average to AIR 42 in SSC CGL',
    slug: 'aspirant-spotlight-salem-ssc-cgl-air-42',
    excerpt:
      'Karthik S. from Periyar University shares his journey overcoming English anxiety, managing a daily 6-hour study regimen at our Salem library, and acing Tier 1 & Tier 2.',
    category: 'Success Stories',
    readTime: '5 min read',
    publishedAt: 'August 14, 2026',
    author: {
      name: 'Stackly Salem Editorial',
      role: 'Student Success Desk',
      avatar: './assets/images/img-1519085360753-af.webp',
    },
    tags: ['SSC CGL', 'Success Story', 'Salem Aspirant', 'Perseverance'],
    image: './assets/images/img-1523240795612-9a.webp',
    featured: false,
    content: [
      'When Karthik first walked into Stackly Salem in October 2025, his diagnostic score in English Comprehension was 14 out of 50. He had completed his engineering degree in Tamil medium and doubted his ability to compete in national central government exams.',
      '"The mentors at Stackly did not hand me an intimidating grammar rulebook," Karthik explains. "Instead, they assigned me 3 editorial passages from The Hindu every morning with sentence deconstruction drills."',
      'By December, his speed in quantitative reasoning had reached 25 questions in 18 minutes through daily computer lab gauntlets. In the final SSC CGL 2026 examination, Karthik secured AIR 42 and joined the Central Secretariat Service Assistant Section Officer.',
      'Karthiks advice to young aspirants in Salem and surrounding districts: "Do not fear central exams because of English. With structured mentorship and consistent mock testing, anyone from our region can compete at the highest national level."',
    ],
  },
  {
    id: 'post-5',
    title: 'Tamil Nadu Current Affairs Monthly Digest: Key Schemes, Infrastructure & Governance Milestones',
    slug: 'tamil-nadu-current-affairs-monthly-digest',
    excerpt:
      'Essential state updates for competitive exams. Complete analysis of new welfare policies, industrial corridor expansions, archaeological excavations, and budget allocations.',
    category: 'Current Affairs',
    readTime: '9 min read',
    publishedAt: 'August 05, 2026',
    author: {
      name: 'M. Anandhi',
      role: 'Research Associate (Public Policy), Salem HQ',
      avatar: './assets/images/img-1573496359142-b8.webp',
    },
    tags: ['Current Affairs', 'Tamil Nadu', 'State Schemes', 'TNPSC'],
    image: './assets/images/img-1541872703-74c5e.webp',
    featured: false,
    content: [
      'Current affairs constitutes 20% to 25% of modern competitive examinations in South India. Rather than reading random headline aggregators, competitive exam aspirants need to understand policy rationale, beneficiary criteria, and economic implications.',
      'Key Highlights Covered in this Digest:',
      '1. Expansion of the Chief Ministers Breakfast Scheme across government-aided primary schools and its measured impact on child nutrition and classroom attendance.',
      '2. The Salem–Coimbatore Defense Industrial Corridor initiatives and newly inaugurated testing facilities in Western Tamil Nadu.',
      '3. Keeladi and Porunai archaeological carbon-dating findings and their integration into Unit 8 syllabus questions.',
      '4. Tamil Nadu Climate Change Mission updates and coastal bio-shield restoration targets.',
    ],
  },
  {
    id: 'post-6',
    title: 'Official Exam Alert: Major Pattern Changes in Bank PO & Clerk Recruitment 2026',
    slug: 'bank-po-pattern-changes-ibps-sbi-2026',
    excerpt:
      'Detailed breakdown of newly introduced sectional time allocations, puzzle complexity changes, and descriptive paper guidelines announced by recruiting bodies.',
    category: 'Exam Alerts',
    readTime: '4 min read',
    publishedAt: 'July 29, 2026',
    author: {
      name: 'R. Vignesh',
      role: 'Banking & Insurance Exam Mentor',
      avatar: './assets/images/img-1500648767791-00.webp',
    },
    tags: ['Bank PO', 'SBI PO', 'IBPS', 'Notification Alert'],
    image: './assets/images/img-1450133064473-71.webp',
    featured: false,
    content: [
      'The Institute of Banking Personnel Selection (IBPS) and State Bank of India have released updated notification standards for the upcoming recruitment cycle.',
      'Key updates every banking aspirant must prepare for:',
      '1. Stricter negative marking penalties for unattempted flagged questions in preliminary testing.',
      '2. Increased weighting on Data Sufficiency and Caselet DI, replacing conventional tabular and bar graph sets.',
      '3. Computer Aptitude and Reasoning sections now include basic logical pseudocode and flow-chart interpretation.',
      'Stacklys banking mock test series has been updated with these exact new pattern papers available at our Salem CBT center and online.',
    ],
  },
];

var STUDY_CHEATSHEETS = window.STUDY_CHEATSHEETS = [
  {
    id: 'cs-1',
    title: 'High-Yield Quantitative Formula Bible (50 Pages)',
    exam: 'GRE / GMAT / CAT / Bank PO',
    fileSize: '3.8 MB PDF',
    downloads: '18,400+',
    badge: 'Most Popular',
  },
  {
    id: 'cs-2',
    title: 'TNPSC Unit 8 & 9 Milestone Timeline & Key Acts (1850–2026)',
    exam: 'TNPSC Group 1, 2 & 4',
    fileSize: '4.2 MB PDF',
    downloads: '24,600+',
    badge: 'Salem Exclusive',
  },
  {
    id: 'cs-3',
    title: 'Essential 800 High-Frequency Academic Vocabulary Flash-Cards',
    exam: 'GRE / IELTS / TOEFL',
    fileSize: '2.5 MB PDF',
    downloads: '15,200+',
    badge: 'Updated 2026',
  },
  {
    id: 'cs-4',
    title: '500 High-Probability General Studies MCQs with Detailed Solutions',
    exam: 'SSC CGL / RRB / TNPSC',
    fileSize: '5.1 MB PDF',
    downloads: '12,900+',
    badge: 'Verified Solutions',
  },
];
